on: [push]

jobs:
  kicad_job:
    runs-on: ubuntu-latest
    name: My KiCad job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export production files
        id: production
        uses: bazhenov/kicad-action
        if: '!cancelled()'
        with:
          kicad_sch: eload.kicad_sch
          sch_pdf: true # Generate PDF
          sch_bom: true # Generate BOM
          kicad_pcb: eload.kicad_pcb
          pcb_gerbers: true # Generate Gerbers
          pcb_image: true

      # Upload production files only if generation succeeded
      - name: Upload production files
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() && steps.production.conclusion == 'success' }}
        with:
          name: Production files
          path: |
            ${{ github.workspace }}/sch.pdf
            ${{ github.workspace }}/bom.csv
            ${{ github.workspace }}/gbr.zip
            ${{ github.workspace }}/images/top.png
            ${{ github.workspace }}/images/bottom.png

      - name: Run KiCad ERC
        id: erc
        uses: bazhenov/kicad-action
        if: '!cancelled()'
        with:
          kicad_version: 9.0.6
          kicad_sch: eload.kicad_sch
          sch_erc: true

      # DRC disabled because we're still in schematic capture phase
      # - name: Run KiCad DRC
      #   id: drc
      #   uses: sparkengineering/kicad-action@v4
      #   if: '!cancelled()'
      #   with:
      #     kicad_pcb: eload.kicad_pcb
      #     pcb_drc: true

      # Upload ERC report only if ERC failed
      - name: Upload ERC report
        uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.erc.conclusion == 'failure' }}
        with:
          name: erc.rpt
          path: ${{ github.workspace }}/erc.rpt

      # Upload DRC report only if DRC failed
      - name: Upload DRC report
        uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.drc.conclusion == 'failure' }}
        with:
          name: drc.rpt
          path: ${{ github.workspace }}/drc.rpt
